Repository DeveloperAshish8/CodeChamp-s-Website, pull requests merged in 2022-10, with the labels that each got.

#50 Fixing contribution guidelines
  CONTRIBUTING.md
  README.md
Labels: documentation

#48 Fixed the responsiveness of why-to-join-us section
  .DS_Store
  images/what we offer image.jpg
  index.html
  style.css
Labels: hacktoberfest-accepted

#58 Dark mode feature added
  .DS_Store
  index.html
  style.css
Labels: hacktoberfest-accepted

#59 preloader guidelines
  ux_design_guidlines/pre-loader.gif
  ux_design_guidlines/pre-loader.md
Labels: hacktoberfest-accepted

#84 Added the social media icons with with hover effect in footer section.
  index.html
  internships.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#81 Link update and navigation problem solved
  internships.html
Labels: enhancement, hacktoberfest-accepted

#82 Added PageUp Button
  index.html
  internship.css
  internships.html
  myScript.js
  style.css
Labels: hacktoberfest-accepted

#90 internship page's layout
  internship.css
  internships.html
Labels: hacktoberfest-accepted

#95 fix: resolved overflowing issue in the internship page and improved internship cards
  internship.css
  internships.html
  style.css
Labels: bug, hacktoberfest-accepted

#70 Preloader added
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#103 Bug/fix collapse nav mobile
  index.html
Labels: Minor Edits

#78 Minor Fixes in Opportunities and Contact Us section
  index.html
  style.css
Labels: Minor Edits

#99 Improved the styling of the internships cards
  internship.css
  internships.html
Labels: enhancement, hacktoberfest-accepted

#45 Added Code of Conduct
  CODE_OF_CONDUCT.md
Labels: documentation, hacktoberfest-accepted

#106 Preloader Added
  index.html
  internships.html
  style.css
Labels: bug, hacktoberfest-accepted

#120 better description of Code Champ
  index.html
  style.css
Labels: documentation, hacktoberfest-accepted

#93 minor changes
  README.md
Labels: enhancement, hacktoberfest-accepted

#121 Scroll-Bar
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#140 Added Buttons in the FAQ section
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#141 feat: added open graph image
  images/opengraph-image.webp
  index.html
Labels: enhancement, hacktoberfest-accepted

#147 Changed hamburger background color
  style.css
Labels: enhancement, hacktoberfest-accepted

#151 Improving the 'Why to join us?' section
  images/what we offer image.jpg
  images/what we offer image.png
  index.html
Labels: documentation, enhancement, hacktoberfest-accepted

#150 Fixes issue #143
  index.html
Labels: bug, hacktoberfest-accepted

#158 Added onscroll active navbar
  index.html
  myScript.js
  style.css
Labels: enhancement, hacktoberfest-accepted

#162 updates #160
  internship.css
  internships.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#173 Update style.css
  style.css
Labels: bug, hacktoberfest-accepted

#179 Better Nav Interface
  style.css
Labels: enhancement, hacktoberfest-accepted

#181 Comment section enhancement
  style.css
Labels: enhancement, hacktoberfest-accepted

#175 updated scroll to top button
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#185 fixed hidden section titles
  index.html
  style.css
Labels: bug, hacktoberfest-accepted

#187 added intern opening at swiggy and McAfee
  internships.html
Labels: documentation, hacktoberfest-accepted

#195 fixed navbar 992-1200px
  style.css
Labels: bug, hacktoberfest-accepted

#197 Modified Navbar
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#201 Issue Updated #194
  style.css
Labels: enhancement, hacktoberfest-accepted
